#!/bin/sh

post_sysupgrade()
{
	if grep -q '^[^#].*frugalware-current$' /etc/pacman-g2.conf; then
		fdb="/var/lib/pacman-g2/frugalware-current.fdb"
		if tar tf $fdb |grep -q '^\.version'; then
			sed -i "s/ \(.*\) (/ `tar xOf $fdb .version` (/" /etc/frugalware-release
			if [ -e /boot/grub/grub.cfg ]; then
				if ! grep -q "GRUB_DISTRIBUTOR=\"$(cat /etc/frugalware-release)\"" /etc/default/grub; then
					sed -i "s/.*GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR=\"`cat /etc/frugalware-release`\"/" \
						/etc/default/grub
					grub-mkconfig -o /boot/grub/grub.cfg > /dev/null 2>&1
				fi
			fi
		fi
	fi
}

op=$1
shift
$op $*
