#!/bin/sh

post_sysupgrade()
{
	if grep -q '^[^#].*frugalware-current$' /etc/pacman-g2.conf; then
		fdb="/var/lib/pacman-g2/frugalware-current.fdb"
		if tar tf $fdb |grep -q '^\.version'; then
			sed -i "s/ \(.*\) (/ `tar xOf $fdb .version` (/" /etc/frugalware-release
			if [ -e /boot/grub/menu.lst ]; then
				sed -i "s/Frugalware .*)/`cat /etc/frugalware-release`/" \
					/boot/grub/menu.lst
			elif [ -e /etc/yaboot.conf -a -e /proc/1 -a -e /dev/zero ]; then
				sed -i "s/Frugalware .*)/`cat /etc/frugalware-release`/" \
					/etc/yaboot.conf
				grep -q unconfigured /etc/yaboot.conf || ybin
			fi
		fi
	fi
}

op=$1
shift
$op $*
