#!/bin/sh

# (c) 2003, 2004, 2008, 2010 Miklos Vajna <vmiklos@frugalware.org>
# service for Frugalware
# distributed under GPL License

TEXTDOMAIN=service
TEXTDOMAINDIR=/var/lib/frugalware/messages


usage()
{
	echo $"Usage: $0 service action"
        echo
        echo $"Actions:"
        echo
        echo $"start        Start the service."
        echo
        echo $"stop         Stop the service."
        echo
        echo $"status       Status of the service (if it supports querying so)."
        echo
        echo $"restart      Stop and start again the service."
        echo
        echo $"add          Adds a new service for management by chkconfig."
        echo
        echo $"del          Removes a service from chkconfig management."
        echo
        echo $"list         List whether the service is stopped or started in each runlevel."  
        exit 0
}

if [ "$1" = "" ]; then
	usage
fi

if [ "$1" = "--version" ]; then
	echo "service (pacman-tools) 0.2.1"
	echo
	echo "Copyright (c) 2003-2010 by Miklos Vajna <vmiklos@frugalware.org>"
	echo "This is free software; see the source for copying conditions.  There is NO"
	echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
	exit 0
elif [ "$1" = "--help" ]; then
	usage
fi

if [ "$1" = "level" ]; then
	# this is undocumented, so we can avoid adding systemd support here
	if [ "$2" != "" ]; then
		if [ "$3" != "" ]; then
			## well just support english for now 'on' is not 
			## the same as Ein etc 
			LC_ALL=C; chkconfig --list --level $2 | grep $2:$3
		else
			echo $"Usage: $0 level <level> <on/off>"
			exit 1
		fi
	else
		echo $"Usage: $0 level <level> <on/off>"
		exit 1
	fi
else
	if [ -e /etc/rc.d/rc.$1 ]; then
	service=rc.$1
	name=/etc/rc.d/$service
	if ! [ -z "$1" ]; then
		if ! [ -e $name ]; then
			## maybe typo ?
			usage
			exit 1
		fi
	fi
	if [ "$2" = "add" ]; then
		chkconfig --add $service
	elif [ "$2" = "del" ]; then
		chkconfig --del $service
	elif [ "$2" = "list" ]; then
		chkconfig --list $service >/dev/null 2>&1
		RET=$?
		if [ "$RET" = "0" ]; then
			## we are fine , the file $name 
			## exists and is added  list it
			chkconfig --list $service
		else
			# we mimic the wished output of chkconfig
			echo -e $service'\t\t0:off\t1:off\t2:off\t3:off\t4:off\t5:off\t6:off'
		fi
	else
		$name $2
	fi
	else
		# no such init script? let's give systemd a try, then
		service=$1.service
		if [ "$2" = "add" ]; then
			systemctl enable $service
		elif [ "$2" = "del" ]; then
			systemctl disable $service
		elif [ "$2" = "list" ]; then
			if systemctl is-enabled $service; then
				echo enabled
			else
				echo disabled
			fi
		else
			systemctl $2 $service
		fi
	fi
fi
