#!/bin/sh

# (c) 2003-2004 Vajna Miklos <vmiklos@frugalware.org>
# service for Frugalware
# distributed under GPL License

TEXTDOMAIN=service
TEXTDOMAINDIR=/var/lib/frugalware/messages

if [ "$1" = "--version" ]; then
	echo "fwmirror (pacman-tools) 0.2"
	echo
	echo "Copyright (c) 2003-2007 by Miklos Vajna <vmiklos@frugalware.org>"
	echo "This is free software; see the source for copying conditions.  There is NO"
	echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
	exit 0
elif [ "$1" = "--help" ]; then
	echo $"Usage: $0 service action"
	echo
	echo $"Actions:"
	echo
	echo $"start        Start the service."
	echo
	echo $"stop         Stop the service."
	echo
	echo $"restart      Stop and start again the service."
	echo
	echo $"add          Adds a new service for management by chkconfig."
	echo
	echo $"del          Removes a service from chkconfig management."
	echo
	echo $"list         List whether the service is stopped or started in each runlevel."
	exit 0
fi
if [ "$1" = "list" ]; then
	chkconfig --list --level $2 | grep $2:$3
else
service=rc.$1
name=/etc/rc.d/$service
if ! [ -z "$1" ]; then
	if ! [ -e $name ]; then
		# this will print a nice error message
		chkconfig --list $service
		exit 1
	fi
	if ! chkconfig --list $service >/dev/null 2>&1; then
		chkconfig --list $service
		exit 1
	fi
fi
if [ "$2" = "start" ]; then
	$name start
elif [ "$2" = "stop" ]; then
	$name stop
elif [ "$2" = "restart" ]; then
	$name restart
elif [ "$2" = "add" ]; then
	chkconfig --add $service
elif [ "$2" = "del" ]; then
	chkconfig --del $service
elif [ "$2" = "list" ]; then
	chkconfig --list $service
  fi
fi
